### ISSUE TITLE
Change position no longer working

### ISSUE THREAD

**Issue by eavanvalkenburg** [MattJeanes/brunt-api#1]
Hi, based on your code I created a python version of this (https://github.com/eavanvalkenburg/brunt-api) but since yesterday change position doesn't work anymore, are you experiencing the same? I get 504 Server Error: GATEWAY_TIMEOUT for url: https://thing.brunt.co:8080/thing/hub/00140d6f1950f166 from that call (even though status etc. does work to the same host and path!)

**Comment by AmyJeanes** [comment]
Hi there, cool python version btw! Just tried it out on my Brunt Blind Engine and its working on my end just fine. I had a quick look at your code but nothing super obvious, though I'm by no means a python expert. Are you gathering a new session id before making a batch of calls? I found if you try and store it long term it won't work.

**Comment by AmyJeanes** [comment]
To clarify, I tried out my own npm version to control my blinds, not your version. Maybe see if my one works? If so, might be an issue in your port.

**Comment by eavanvalkenburg** [comment]
I'm getting some intermittent behaviour on my end (seems to work on and off now). Good point on the session id, I now store the cookie in a Session object, but I'm not sure if and when I get a new one, I'll add something for that.
